<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><OutputType>Exe</OutputType><Nullable>annotations</Nullable></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../Shared/RacingBois.NetworkMapping/RacingBois.NetworkMapping.csproj" /></ItemGroup>
  <ItemGroup><Compile Include="../../../Assets/RacingBois/Client/Application/*.cs" Link="Application/%(Filename)%(Extension)" /></ItemGroup>
</Project>
