// Generated from author-client.tsv. Scoped display copy only.
using System.Collections.Generic;
using RacingBois.Gameplay.Definitions;
namespace RacingBois.Client.Application
{
    public static partial class UiText
    {
        static partial void AddClientMessages(Dictionary<string, string[]> rows)
        {
            rows.Add("client.config.invalid", new[] { "Server configuration is invalid. Using LAN mode on this computer; fix RacingBois.runtime.json to play online.", "Die Serverkonfiguration ist ung\u00fcltig. Dieser Computer verwendet den LAN-Modus. Korrigiere RacingBois.runtime.json, um online zu spielen.", "La configuraci\u00f3n del servidor no es v\u00e1lida. Se usar\u00e1 el modo LAN en este equipo; corrige RacingBois.runtime.json para jugar en l\u00ednea.", "La configuration du serveur est invalide. Le mode LAN est utilis\u00e9 sur cet ordinateur ; corrigez RacingBois.runtime.json pour jouer en ligne.", "La configurazione del server non \u00e8 valida. Verr\u00e0 usata la modalit\u00e0 LAN su questo computer; correggi RacingBois.runtime.json per giocare online.", "C\u1ea5u h\u00ecnh m\u00e1y ch\u1ee7 kh\u00f4ng h\u1ee3p l\u1ec7. \u0110ang d\u00f9ng ch\u1ebf \u0111\u1ed9 LAN t\u1ea1i m\u00e1y n\u00e0y; h\u00e3y s\u1eeda RacingBois.runtime.json \u0111\u1ec3 ch\u01a1i online." });
            rows.Add("client.storage.read", new[] { "The browser cannot read the saved profile. Allow site storage or choose New guest.", "Der Browser kann das gespeicherte Profil nicht lesen. Erlaube das Speichern von Websitedaten oder w\u00e4hle Neuer Gast.", "El navegador no puede leer el perfil guardado. Permite el almacenamiento del sitio o elige Nuevo invitado.", "Le navigateur ne peut pas lire le profil enregistr\u00e9. Autorisez le stockage du site ou choisissez Nouvel invit\u00e9.", "Il browser non pu\u00f2 leggere il profilo salvato. Consenti al sito di salvare dati oppure scegli Nuovo ospite.", "Tr\u00ecnh duy\u1ec7t kh\u00f4ng cho \u0111\u1ecdc h\u1ed3 s\u01a1 \u0111\u00e3 l\u01b0u. H\u00e3y cho ph\u00e9p l\u01b0u d\u1eef li\u1ec7u trang ho\u1eb7c ch\u1ecdn Kh\u00e1ch m\u1edbi." });
            rows.Add("client.storage.write", new[] { "Cannot save data on this device. This session can continue, but restarting may lose your profile or reserved place.", "Auf diesem Ger\u00e4t k\u00f6nnen keine Daten gespeichert werden. Diese Sitzung kann weiterlaufen, aber nach einem Neustart sind dein Profil oder dein reservierter Platz m\u00f6glicherweise nicht wiederherstellbar.", "No se pueden guardar datos en este dispositivo. La sesi\u00f3n puede continuar, pero al reiniciar podr\u00edas perder el perfil o la plaza reservada.", "Impossible d'enregistrer les donn\u00e9es sur cet appareil. La session peut continuer, mais un red\u00e9marrage risque de faire perdre le profil ou la place r\u00e9serv\u00e9e.", "Impossibile salvare dati su questo dispositivo. La sessione pu\u00f2 continuare, ma dopo un riavvio potresti perdere il profilo o il posto riservato.", "Kh\u00f4ng th\u1ec3 l\u01b0u d\u1eef li\u1ec7u tr\u00ean thi\u1ebft b\u1ecb. Phi\u00ean n\u00e0y v\u1eabn ch\u1ea1y, nh\u01b0ng kh\u1edfi \u0111\u1ed9ng l\u1ea1i c\u00f3 th\u1ec3 kh\u00f4ng kh\u00f4i ph\u1ee5c h\u1ed3 s\u01a1 ho\u1eb7c ch\u1ed7 \u0111ang gi\u1eef." });
            rows.Add("content.route.unavailable", new[] { "This route does not have a ready content pack yet.", "F\u00fcr diese Strecke ist noch kein Inhaltspaket verf\u00fcgbar.", "Esta ruta todav\u00eda no tiene un paquete de contenido listo.", "Aucun pack de contenu n'est encore pr\u00eat pour ce parcours.", "Per questo percorso non \u00e8 ancora disponibile un pacchetto di contenuti.", "\u0110\u01b0\u1eddng \u0111ua n\u00e0y ch\u01b0a c\u00f3 g\u00f3i n\u1ed9i dung s\u1eb5n s\u00e0ng." });
            rows.Add("content.checking", new[] { "Checking the content pack\u2026", "Inhaltspaket wird gepr\u00fcft\u2026", "Comprobando el paquete de contenido\u2026", "V\u00e9rification du pack de contenu\u2026", "Verifica del pacchetto di contenuti\u2026", "\u0110ang ki\u1ec3m tra g\u00f3i n\u1ed9i dung\u2026" });
            rows.Add("content.actors.loading", new[] { "Loading bikes and riders\u2026", "Motorr\u00e4der und Fahrer werden geladen\u2026", "Cargando motos y pilotos\u2026", "Chargement des motos et des pilotes\u2026", "Caricamento di moto e piloti\u2026", "\u0110ang t\u1ea3i xe v\u00e0 tay \u0111ua\u2026" });
            rows.Add("content.route.loading", new[] { "Loading {route}\u2026", "{route} wird geladen\u2026", "Cargando {route}\u2026", "Chargement de {route}\u2026", "Caricamento di {route}\u2026", "\u0110ang t\u1ea3i {route}\u2026" });
            rows.Add("content.ready", new[] { "Content is ready.", "Inhalte sind bereit.", "El contenido est\u00e1 listo.", "Le contenu est pr\u00eat.", "I contenuti sono pronti.", "N\u1ed9i dung \u0111\u00e3 s\u1eb5n s\u00e0ng." });
            rows.Add("content.catalog.failed", new[] { "Could not load the content catalog. Check your connection and try again.", "Der Inhaltskatalog konnte nicht geladen werden. Pr\u00fcfe deine Verbindung und versuche es erneut.", "No se pudo cargar el cat\u00e1logo de contenido. Comprueba la conexi\u00f3n e int\u00e9ntalo de nuevo.", "Impossible de charger le catalogue de contenu. V\u00e9rifiez votre connexion et r\u00e9essayez.", "Impossibile caricare il catalogo dei contenuti. Controlla la connessione e riprova.", "Kh\u00f4ng t\u1ea3i \u0111\u01b0\u1ee3c danh m\u1ee5c n\u1ed9i dung. H\u00e3y ki\u1ec3m tra k\u1ebft n\u1ed1i v\u00e0 th\u1eed l\u1ea1i." });
            rows.Add("content.download.interrupted", new[] { "Content download was interrupted. Please try again.", "Der Inhaltsdownload wurde unterbrochen. Bitte versuche es erneut.", "La descarga de contenido se ha interrumpido. Int\u00e9ntalo de nuevo.", "Le t\u00e9l\u00e9chargement du contenu a \u00e9t\u00e9 interrompu. Veuillez r\u00e9essayer.", "Il download dei contenuti \u00e8 stato interrotto. Riprova.", "T\u1ea3i n\u1ed9i dung b\u1ecb gi\u00e1n \u0111o\u1ea1n. H\u00e3y th\u1eed l\u1ea1i." });
            rows.Add("content.bundle.invalid", new[] { "The content pack is damaged or incompatible with this version.", "Das Inhaltspaket ist besch\u00e4digt oder mit dieser Version nicht kompatibel.", "El paquete de contenido est\u00e1 da\u00f1ado o no es compatible con esta versi\u00f3n.", "Le pack de contenu est endommag\u00e9 ou incompatible avec cette version.", "Il pacchetto di contenuti \u00e8 danneggiato o incompatibile con questa versione.", "G\u00f3i n\u1ed9i dung b\u1ecb l\u1ed7i ho\u1eb7c kh\u00f4ng ph\u00f9 h\u1ee3p phi\u00ean b\u1ea3n n\u00e0y." });
            rows.Add("content.version.unavailable", new[] { "Content is not ready or belongs to another game version. Restart or try again.", "Die Inhalte sind noch nicht bereit oder geh\u00f6ren zu einer anderen Spielversion. Starte neu oder versuche es erneut.", "El contenido no est\u00e1 listo o corresponde a otra versi\u00f3n del juego. Reinicia o vuelve a intentarlo.", "Le contenu n'est pas pr\u00eat ou correspond \u00e0 une autre version du jeu. Red\u00e9marrez ou r\u00e9essayez.", "I contenuti non sono pronti o appartengono a un'altra versione del gioco. Riavvia o riprova.", "N\u1ed9i dung ch\u01b0a s\u1eb5n s\u00e0ng ho\u1eb7c kh\u00e1c phi\u00ean b\u1ea3n tr\u00f2 ch\u01a1i. H\u00e3y kh\u1edfi \u0111\u1ed9ng l\u1ea1i ho\u1eb7c th\u1eed l\u1ea1i." });
            rows.Add("client.endpoint.credentials", new[] { "Enter a valid ws:// or wss:// address without login credentials.", "Gib eine g\u00fcltige ws://- oder wss://-Adresse ohne Anmeldedaten ein.", "Introduce una direcci\u00f3n ws:// o wss:// v\u00e1lida, sin credenciales de acceso.", "Saisissez une adresse ws:// ou wss:// valide, sans identifiants de connexion.", "Inserisci un indirizzo ws:// o wss:// valido, senza credenziali di accesso.", "C\u1ea7n \u0111\u1ecba ch\u1ec9 ws:// ho\u1eb7c wss:// h\u1ee3p l\u1ec7, kh\u00f4ng ch\u1ee9a th\u00f4ng tin \u0111\u0103ng nh\u1eadp." });
            rows.Add("client.endpoint.invalid", new[] { "Enter a valid ws:// or wss:// address.", "Gib eine g\u00fcltige ws://- oder wss://-Adresse ein.", "Introduce una direcci\u00f3n ws:// o wss:// v\u00e1lida.", "Saisissez une adresse ws:// ou wss:// valide.", "Inserisci un indirizzo ws:// o wss:// valido.", "C\u1ea7n \u0111\u1ecba ch\u1ec9 ws:// ho\u1eb7c wss:// h\u1ee3p l\u1ec7." });
            rows.Add("client.player.name.invalid", new[] { "Player names must contain 1\u201324 characters and no formatting codes.", "Spielernamen m\u00fcssen 1\u201324 Zeichen lang sein und d\u00fcrfen keine Formatierungscodes enthalten.", "El nombre del jugador debe tener entre 1 y 24 caracteres, sin c\u00f3digos de formato.", "Le nom du joueur doit contenir de 1 \u00e0 24 caract\u00e8res, sans codes de mise en forme.", "Il nome del giocatore deve contenere da 1 a 24 caratteri, senza codici di formattazione.", "T\u00ean ng\u01b0\u1eddi ch\u01a1i c\u1ea7n 1\u201324 k\u00fd t\u1ef1, kh\u00f4ng ch\u1ee9a m\u00e3 \u0111\u1ecbnh d\u1ea1ng." });
            rows.Add("client.room.settings.invalid", new[] { "The room name or opponent count is invalid.", "Der Raumname oder die Anzahl der Gegner ist ung\u00fcltig.", "El nombre de la sala o el n\u00famero de rivales no es v\u00e1lido.", "Le nom du salon ou le nombre d'adversaires est invalide.", "Il nome della stanza o il numero di avversari non \u00e8 valido.", "T\u00ean ph\u00f2ng ho\u1eb7c s\u1ed1 \u0111\u1ed1i th\u1ee7 kh\u00f4ng h\u1ee3p l\u1ec7." });
            rows.Add("client.course.unavailable", new[] { "This route is locked or the level is invalid.", "Diese Strecke ist gesperrt oder die Stufe ist ung\u00fcltig.", "La ruta est\u00e1 bloqueada o el nivel no es v\u00e1lido.", "Ce parcours est verrouill\u00e9 ou le niveau est invalide.", "Il percorso \u00e8 bloccato o il livello non \u00e8 valido.", "Ch\u1eb7ng \u0111ua ch\u01b0a m\u1edf ho\u1eb7c c\u1ea5p kh\u00f4ng h\u1ee3p l\u1ec7." });
            rows.Add("client.room.code.invalid", new[] { "The room code is invalid.", "Der Raumcode ist ung\u00fcltig.", "El c\u00f3digo de sala no es v\u00e1lido.", "Le code du salon est invalide.", "Il codice della stanza non \u00e8 valido.", "M\u00e3 ph\u00f2ng kh\u00f4ng h\u1ee3p l\u1ec7." });
            rows.Add("client.server.ack.missing", new[] { "Server acknowledgments were lost.", "Best\u00e4tigungen des Servers sind ausgeblieben.", "Se han perdido las confirmaciones del servidor.", "Les confirmations du serveur ont \u00e9t\u00e9 perdues.", "Le conferme del server sono andate perse.", "M\u1ea5t x\u00e1c nh\u1eadn t\u1eeb m\u00e1y ch\u1ee7." });
            rows.Add("client.timeline.resync", new[] { "The timeline needs to be synchronized again.", "Der Zeitablauf muss neu synchronisiert werden.", "Es necesario volver a sincronizar la l\u00ednea temporal.", "La chronologie doit \u00eatre resynchronis\u00e9e.", "\u00c8 necessario sincronizzare di nuovo la sequenza temporale.", "D\u00f2ng th\u1eddi gian c\u1ea7n \u0111\u1ed3ng b\u1ed9 l\u1ea1i." });
            rows.Add("client.disconnect.unconfirmed", new[] { "Connection closed; the server has not confirmed leaving the session.", "Verbindung geschlossen; der Server hat das Verlassen der Sitzung noch nicht best\u00e4tigt.", "Conexi\u00f3n cerrada; el servidor a\u00fan no ha confirmado la salida de la sesi\u00f3n.", "Connexion ferm\u00e9e ; le serveur n'a pas confirm\u00e9 la sortie de la session.", "Connessione chiusa; il server non ha ancora confermato l'uscita dalla sessione.", "\u0110\u00e3 \u0111\u00f3ng k\u1ebft n\u1ed1i; m\u00e1y ch\u1ee7 ch\u01b0a x\u00e1c nh\u1eadn tho\u00e1t phi\u00ean." });
            rows.Add("client.connect.timeout", new[] { "The connection timed out.", "Die Verbindung hat das Zeitlimit \u00fcberschritten.", "Se ha agotado el tiempo de conexi\u00f3n.", "Le d\u00e9lai de connexion a expir\u00e9.", "Tempo di connessione scaduto.", "K\u1ebft n\u1ed1i qu\u00e1 th\u1eddi gian ch\u1edd." });
            rows.Add("client.server.unresponsive", new[] { "The server is not responding.", "Der Server antwortet nicht.", "El servidor no responde.", "Le serveur ne r\u00e9pond pas.", "Il server non risponde.", "M\u00e1y ch\u1ee7 kh\u00f4ng ph\u1ea3n h\u1ed3i." });
            rows.Add("client.session.suspended_before_welcome", new[] { "The session was suspended before connection details arrived.", "Die Sitzung wurde angehalten, bevor die Verbindungsdaten eingetroffen sind.", "La sesi\u00f3n se suspendi\u00f3 antes de recibir los datos de conexi\u00f3n.", "La session a \u00e9t\u00e9 suspendue avant la r\u00e9ception des informations de connexion.", "La sessione \u00e8 stata sospesa prima di ricevere i dati di connessione.", "Phi\u00ean \u0111\u00e3 t\u1ea1m d\u1eebng tr\u01b0\u1edbc khi nh\u1eadn th\u00f4ng tin k\u1ebft n\u1ed1i." });
            rows.Add("client.session.restoring", new[] { "Restoring the session\u2026", "Sitzung wird wiederhergestellt\u2026", "Restaurando la sesi\u00f3n\u2026", "Restauration de la session\u2026", "Ripristino della sessione\u2026", "\u0110ang kh\u00f4i ph\u1ee5c phi\u00ean\u2026" });
            rows.Add("client.session.other_tab", new[] { "This session is open in another tab. Choose New guest to play as another player.", "Diese Sitzung ist in einem anderen Tab ge\u00f6ffnet. W\u00e4hle Neuer Gast, um als weiterer Spieler mitzuspielen.", "Esta sesi\u00f3n est\u00e1 abierta en otra pesta\u00f1a. Elige Nuevo invitado para jugar con otro jugador.", "Cette session est ouverte dans un autre onglet. Choisissez Nouvel invit\u00e9 pour jouer avec un autre joueur.", "Questa sessione \u00e8 aperta in un'altra scheda. Scegli Nuovo ospite per giocare con un altro giocatore.", "Phi\u00ean \u0111\u00e3 \u0111\u01b0\u1ee3c m\u1edf \u1edf th\u1ebb kh\u00e1c. Ch\u1ecdn Kh\u00e1ch m\u1edbi \u0111\u1ec3 ch\u01a1i th\u00eam m\u1ed9t ng\u01b0\u1eddi." });
            rows.Add("client.leave.unconfirmed", new[] { "The server has not confirmed leaving the session.", "Der Server hat das Verlassen der Sitzung noch nicht best\u00e4tigt.", "El servidor a\u00fan no ha confirmado la salida de la sesi\u00f3n.", "Le serveur n'a pas confirm\u00e9 la sortie de la session.", "Il server non ha ancora confermato l'uscita dalla sessione.", "M\u00e1y ch\u1ee7 ch\u01b0a x\u00e1c nh\u1eadn tho\u00e1t phi\u00ean." });
            rows.Add("client.connection.interrupted", new[] { "The connection was interrupted.", "Die Verbindung wurde unterbrochen.", "La conexi\u00f3n se ha interrumpido.", "La connexion a \u00e9t\u00e9 interrompue.", "La connessione \u00e8 stata interrotta.", "K\u1ebft n\u1ed1i b\u1ecb gi\u00e1n \u0111o\u1ea1n." });
            rows.Add("client.session.restore.failed", new[] { "Could not restore the session. Please reconnect.", "Die Sitzung konnte nicht wiederhergestellt werden. Bitte verbinde dich erneut.", "No se pudo restaurar la sesi\u00f3n. Vuelve a conectarte.", "Impossible de restaurer la session. Veuillez vous reconnecter.", "Impossibile ripristinare la sessione. Riconnettiti.", "Kh\u00f4ng kh\u00f4i ph\u1ee5c \u0111\u01b0\u1ee3c phi\u00ean. H\u00e3y k\u1ebft n\u1ed1i l\u1ea1i." });
            rows.Add("client.connect.required", new[] { "Not connected to the server.", "Keine Verbindung zum Server.", "No hay conexi\u00f3n con el servidor.", "Aucune connexion au serveur.", "Nessuna connessione al server.", "Ch\u01b0a k\u1ebft n\u1ed1i m\u00e1y ch\u1ee7." });
            rows.Add("client.room.required", new[] { "You have not joined a room.", "Du bist keinem Raum beigetreten.", "No te has unido a ninguna sala.", "Vous n'avez rejoint aucun salon.", "Non sei in nessuna stanza.", "Ch\u01b0a tham gia ph\u00f2ng." });
            rows.Add("client.response.too_large", new[] { "The server response exceeds the limit.", "Die Serverantwort \u00fcberschreitet das Limit.", "La respuesta del servidor supera el l\u00edmite.", "La r\u00e9ponse du serveur d\u00e9passe la limite.", "La risposta del server supera il limite.", "Ph\u1ea3n h\u1ed3i m\u00e1y ch\u1ee7 v\u01b0\u1ee3t gi\u1edbi h\u1ea1n." });
            rows.Add("client.response.invalid", new[] { "Server data is invalid. The session stopped to resynchronize safely.", "Die Serverdaten sind ung\u00fcltig. Die Sitzung wurde f\u00fcr eine sichere Neusynchronisierung angehalten.", "Los datos del servidor no son v\u00e1lidos. La sesi\u00f3n se ha detenido para sincronizarse con seguridad.", "Les donn\u00e9es du serveur sont invalides. La session a \u00e9t\u00e9 arr\u00eat\u00e9e pour une resynchronisation s\u00fbre.", "I dati del server non sono validi. La sessione \u00e8 stata interrotta per una risincronizzazione sicura.", "D\u1eef li\u1ec7u m\u00e1y ch\u1ee7 kh\u00f4ng h\u1ee3p l\u1ec7. Phi\u00ean \u0111\u00e3 d\u1eebng \u0111\u1ec3 \u0111\u1ed3ng b\u1ed9 an to\u00e0n." });
            rows.Add("client.state.missing", new[] { "A state message is missing. Recovering\u2026", "Eine Statusnachricht fehlt. Wiederherstellung l\u00e4uft\u2026", "Falta un mensaje de estado. Recuperando\u2026", "Un message d'\u00e9tat est manquant. R\u00e9cup\u00e9ration en cours\u2026", "Manca un messaggio di stato. Ripristino in corso\u2026", "Thi\u1ebfu th\u00f4ng \u0111i\u1ec7p tr\u1ea1ng th\u00e1i. \u0110ang kh\u00f4i ph\u1ee5c\u2026" });
        }
        static partial void TranslateClientMessage(string locale, string raw, ref string translated)
        {
            switch (raw)
            {
                case "C\u1ea5u h\u00ecnh m\u00e1y ch\u1ee7 kh\u00f4ng h\u1ee3p l\u1ec7. \u0110ang d\u00f9ng ch\u1ebf \u0111\u1ed9 LAN t\u1ea1i m\u00e1y n\u00e0y; h\u00e3y s\u1eeda RacingBois.runtime.json \u0111\u1ec3 ch\u01a1i online.": translated = Get(locale, "client.config.invalid"); return;
                case "Tr\u00ecnh duy\u1ec7t kh\u00f4ng cho \u0111\u1ecdc h\u1ed3 s\u01a1 \u0111\u00e3 l\u01b0u. H\u00e3y cho ph\u00e9p l\u01b0u d\u1eef li\u1ec7u trang ho\u1eb7c ch\u1ecdn Kh\u00e1ch m\u1edbi.": translated = Get(locale, "client.storage.read"); return;
                case "Kh\u00f4ng th\u1ec3 l\u01b0u d\u1eef li\u1ec7u tr\u00ean thi\u1ebft b\u1ecb. Phi\u00ean n\u00e0y v\u1eabn ch\u1ea1y, nh\u01b0ng kh\u1edfi \u0111\u1ed9ng l\u1ea1i c\u00f3 th\u1ec3 kh\u00f4ng kh\u00f4i ph\u1ee5c h\u1ed3 s\u01a1 ho\u1eb7c ch\u1ed7 \u0111ang gi\u1eef.": translated = Get(locale, "client.storage.write"); return;
                case "\u0110\u01b0\u1eddng \u0111ua n\u00e0y ch\u01b0a c\u00f3 g\u00f3i n\u1ed9i dung s\u1eb5n s\u00e0ng.": translated = Get(locale, "content.route.unavailable"); return;
                case "\u0110ang ki\u1ec3m tra g\u00f3i n\u1ed9i dung\u2026": translated = Get(locale, "content.checking"); return;
                case "\u0110ang t\u1ea3i xe v\u00e0 tay \u0111ua\u2026": translated = Get(locale, "content.actors.loading"); return;
                case "N\u1ed9i dung \u0111\u00e3 s\u1eb5n s\u00e0ng.": translated = Get(locale, "content.ready"); return;
                case "Kh\u00f4ng t\u1ea3i \u0111\u01b0\u1ee3c danh m\u1ee5c n\u1ed9i dung. H\u00e3y ki\u1ec3m tra k\u1ebft n\u1ed1i v\u00e0 th\u1eed l\u1ea1i.": translated = Get(locale, "content.catalog.failed"); return;
                case "T\u1ea3i n\u1ed9i dung b\u1ecb gi\u00e1n \u0111o\u1ea1n. H\u00e3y th\u1eed l\u1ea1i.": translated = Get(locale, "content.download.interrupted"); return;
                case "G\u00f3i n\u1ed9i dung b\u1ecb l\u1ed7i ho\u1eb7c kh\u00f4ng ph\u00f9 h\u1ee3p phi\u00ean b\u1ea3n n\u00e0y.": translated = Get(locale, "content.bundle.invalid"); return;
                case "N\u1ed9i dung ch\u01b0a s\u1eb5n s\u00e0ng ho\u1eb7c kh\u00e1c phi\u00ean b\u1ea3n tr\u00f2 ch\u01a1i. H\u00e3y kh\u1edfi \u0111\u1ed9ng l\u1ea1i ho\u1eb7c th\u1eed l\u1ea1i.": translated = Get(locale, "content.version.unavailable"); return;
                case "C\u1ea7n \u0111\u1ecba ch\u1ec9 ws:// ho\u1eb7c wss:// h\u1ee3p l\u1ec7, kh\u00f4ng ch\u1ee9a th\u00f4ng tin \u0111\u0103ng nh\u1eadp.": translated = Get(locale, "client.endpoint.credentials"); return;
                case "C\u1ea7n \u0111\u1ecba ch\u1ec9 ws:// ho\u1eb7c wss:// h\u1ee3p l\u1ec7.": translated = Get(locale, "client.endpoint.invalid"); return;
                case "T\u00ean ng\u01b0\u1eddi ch\u01a1i c\u1ea7n 1\u201324 k\u00fd t\u1ef1, kh\u00f4ng ch\u1ee9a m\u00e3 \u0111\u1ecbnh d\u1ea1ng.": translated = Get(locale, "client.player.name.invalid"); return;
                case "T\u00ean ph\u00f2ng ho\u1eb7c s\u1ed1 \u0111\u1ed1i th\u1ee7 kh\u00f4ng h\u1ee3p l\u1ec7.": translated = Get(locale, "client.room.settings.invalid"); return;
                case "Ch\u1eb7ng \u0111ua ch\u01b0a m\u1edf ho\u1eb7c c\u1ea5p kh\u00f4ng h\u1ee3p l\u1ec7.": translated = Get(locale, "client.course.unavailable"); return;
                case "M\u00e3 ph\u00f2ng kh\u00f4ng h\u1ee3p l\u1ec7.": translated = Get(locale, "client.room.code.invalid"); return;
                case "M\u1ea5t x\u00e1c nh\u1eadn t\u1eeb m\u00e1y ch\u1ee7.": translated = Get(locale, "client.server.ack.missing"); return;
                case "D\u00f2ng th\u1eddi gian c\u1ea7n \u0111\u1ed3ng b\u1ed9 l\u1ea1i.": translated = Get(locale, "client.timeline.resync"); return;
                case "\u0110\u00e3 \u0111\u00f3ng k\u1ebft n\u1ed1i; m\u00e1y ch\u1ee7 ch\u01b0a x\u00e1c nh\u1eadn tho\u00e1t phi\u00ean.": translated = Get(locale, "client.disconnect.unconfirmed"); return;
                case "K\u1ebft n\u1ed1i qu\u00e1 th\u1eddi gian ch\u1edd.": translated = Get(locale, "client.connect.timeout"); return;
                case "M\u00e1y ch\u1ee7 kh\u00f4ng ph\u1ea3n h\u1ed3i.": translated = Get(locale, "client.server.unresponsive"); return;
                case "Phi\u00ean \u0111\u00e3 t\u1ea1m d\u1eebng tr\u01b0\u1edbc khi nh\u1eadn th\u00f4ng tin k\u1ebft n\u1ed1i.": translated = Get(locale, "client.session.suspended_before_welcome"); return;
                case "\u0110ang kh\u00f4i ph\u1ee5c phi\u00ean\u2026": translated = Get(locale, "client.session.restoring"); return;
                case "Phi\u00ean \u0111\u00e3 \u0111\u01b0\u1ee3c m\u1edf \u1edf th\u1ebb kh\u00e1c. Ch\u1ecdn Kh\u00e1ch m\u1edbi \u0111\u1ec3 ch\u01a1i th\u00eam m\u1ed9t ng\u01b0\u1eddi.": translated = Get(locale, "client.session.other_tab"); return;
                case "M\u00e1y ch\u1ee7 ch\u01b0a x\u00e1c nh\u1eadn tho\u00e1t phi\u00ean.": translated = Get(locale, "client.leave.unconfirmed"); return;
                case "K\u1ebft n\u1ed1i b\u1ecb gi\u00e1n \u0111o\u1ea1n.": translated = Get(locale, "client.connection.interrupted"); return;
                case "Kh\u00f4ng kh\u00f4i ph\u1ee5c \u0111\u01b0\u1ee3c phi\u00ean. H\u00e3y k\u1ebft n\u1ed1i l\u1ea1i.": translated = Get(locale, "client.session.restore.failed"); return;
                case "Ch\u01b0a k\u1ebft n\u1ed1i m\u00e1y ch\u1ee7.": translated = Get(locale, "client.connect.required"); return;
                case "Ch\u01b0a tham gia ph\u00f2ng.": translated = Get(locale, "client.room.required"); return;
                case "Ph\u1ea3n h\u1ed3i m\u00e1y ch\u1ee7 v\u01b0\u1ee3t gi\u1edbi h\u1ea1n.": translated = Get(locale, "client.response.too_large"); return;
                case "D\u1eef li\u1ec7u m\u00e1y ch\u1ee7 kh\u00f4ng h\u1ee3p l\u1ec7. Phi\u00ean \u0111\u00e3 d\u1eebng \u0111\u1ec3 \u0111\u1ed3ng b\u1ed9 an to\u00e0n.": translated = Get(locale, "client.response.invalid"); return;
                case "Thi\u1ebfu th\u00f4ng \u0111i\u1ec7p tr\u1ea1ng th\u00e1i. \u0110ang kh\u00f4i ph\u1ee5c\u2026": translated = Get(locale, "client.state.missing"); return;
            }
            // Only exact current catalog names on this known loader-status channel are substituted.
            for (int i = 0; i < CampaignCatalog.RouteCount; i++)
            {
                string route = CampaignCatalog.GetRoute(i).DisplayName;
                if (raw == "\u0110ang t\u1ea3i " + route + "\u2026")
                { translated = Format(locale, "content.route.loading", new UiTextArgument("route", route)); return; }
            }
        }
    }
}
