"""Validate all original display-copy translations, then emit only staged C#."""
import hashlib
import json
import re
from pathlib import Path
from prepare_source import HERE, source

LOCALES = ('ENU', 'DEU', 'ESP', 'FRA', 'ITA', 'VI')

def read_unique(path):
    def pairs(items):
        result = {}
        for key, value in items:
            if key in result:
                raise ValueError('Duplicate key: ' + key)
            result[key] = value
        return result
    return json.loads(path.read_text(encoding='utf-8'), object_pairs_hook=pairs)

def validate(locale, payload, expected):
    if payload.get('schema') != 1 or payload.get('locale') != locale:
        raise ValueError('Wrong locale/schema: ' + locale)
    if payload.get('sourceSha256') != expected['sourceSha256'] or payload.get('storyboardsSha256') != expected['storyboardsSha256']:
        raise ValueError('Stale authored source binding: ' + locale)
    values = payload.get('strings', {})
    if set(values) != set(expected['strings']):
        raise ValueError('Missing/extra keys: ' + locale)
    for key, value in values.items():
        if not isinstance(value, str) or not value.strip() or value != value.strip() or any(ord(c) < 32 for c in value):
            raise ValueError('Invalid display copy: ' + locale + '/' + key)
        if re.findall(r'\{[^}]*\}', value) != re.findall(r'\{[^}]*\}', expected['strings'][key]):
            raise ValueError('Format placeholder mismatch: ' + locale + '/' + key)
        if '{' in re.sub(r'\{0\}', '', value) or '}' in re.sub(r'\{0\}', '', value):
            raise ValueError('Invalid format braces: ' + locale + '/' + key)
    if locale == 'ENU' and values != expected['strings']:
        raise ValueError('English source changed')
    return values

def generate():
    expected = source()
    catalogs = {locale: validate(locale, read_unique(HERE / 'locales' / (locale + '.json')), expected) for locale in LOCALES}
    lines = ['// Generated by tools/p08/media/localization-staging/generate.py; edit bound locale JSON, not this file.',
             'using System;', 'using System.Collections.Generic;', 'namespace RacingBois.Client.Application', '{',
             '    public static partial class CinematicText', '    {',
             '        public const string SourceSha256 = "' + expected['sourceSha256'] + '";',
             '        public const int KeyCount = ' + str(len(expected['strings'])) + ';',
             '        private static readonly Dictionary<string, string[]> Rows = new Dictionary<string, string[]>(StringComparer.Ordinal)', '        {']
    for key in sorted(expected['strings']):
        cells = ', '.join(json.dumps(catalogs[locale][key], ensure_ascii=True) for locale in LOCALES)
        lines.append('            { ' + json.dumps(key) + ', new[] { ' + cells + ' } },')
    lines += ['        };', '    }', '}']
    output = HERE / 'CinematicText.Generated.cs'
    output.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    result = {'schema': 1, 'sourceSha256': expected['sourceSha256'], 'keysPerLocale': len(expected['strings']), 'locales': list(LOCALES),
              'generatedSha256': hashlib.sha256(output.read_bytes()).hexdigest(), 'linguisticAcceptance': False,
              'nativeReadabilityAcceptance': False, 'fullGameLocalizationAcceptance': False}
    (HERE / 'coverage.json').write_text(json.dumps(result, indent=2) + '\n', encoding='utf-8')
    print(json.dumps(result))

if __name__ == '__main__':
    generate()
