// VI-only managed test fixture. Empty other-locale cells are never shipped or claimed as translations.
using System.Collections.Generic;
namespace RacingBois.Client.Application {
 public static partial class UiText {
  static partial void AddCareer(Dictionary<string,string[]> rows) {
   rows.Add("career.account.connectToRegister", new[] { "", "", "", "", "", "KẾT NỐI HỒ SƠ ĐỂ ĐĂNG KÝ" });
   rows.Add("career.account.expiredCredentialHint", new[] { "", "", "", "", "", "Khóa hồ sơ đang lưu đã hết hạn hoặc bị thu hồi. Tài khoản đã đăng ký vẫn có thể đăng nhập hoặc khôi phục ở trên." });
   rows.Add("career.account.forgetCredential", new[] { "", "", "", "", "", "BỎ KHÓA HỒ SƠ ĐÃ HẾT HẠN" });
   rows.Add("career.account.forgetCredentialConfirm", new[] { "", "", "", "", "", "Bỏ khóa cũ trên máy này? Bạn sẽ không còn truy cập hồ sơ vô danh cũ bằng khóa này. Nếu đã nâng cấp tài khoản, hãy đăng nhập hoặc khôi phục tài khoản để giữ tiến trình; bản sao lưu máy chủ vẫn cần cơ chế khôi phục của chủ máy. Sau khi bỏ khóa, KẾT NỐI HỒ SƠ sẽ tạo hồ sơ mới." });
   rows.Add("career.account.heading", new[] { "", "", "", "", "", "GIỮ LẠI HÀNH TRÌNH CỦA BẠN." });
   rows.Add("career.account.loggedIn", new[] { "", "", "", "", "", "ĐANG ĐĂNG NHẬP: {username}" });
   rows.Add("career.account.login", new[] { "", "", "", "", "", "ĐĂNG NHẬP" });
   rows.Add("career.account.logout", new[] { "", "", "", "", "", "ĐĂNG XUẤT MÁY NÀY" });
   rows.Add("career.account.logoutAll", new[] { "", "", "", "", "", "THU HỒI TẤT CẢ PHIÊN" });
   rows.Add("career.account.logoutAllConfirm", new[] { "", "", "", "", "", "Đăng xuất tất cả phiên của tài khoản? Bạn cần đăng nhập lại trên từng máy." });
   rows.Add("career.account.logoutConfirm", new[] { "", "", "", "", "", "Thu hồi khóa hồ sơ trên máy này và kết thúc phiên hiện tại?" });
   rows.Add("career.account.newRecoveryNotice", new[] { "", "", "", "", "", "LƯU MÃ KHÔI PHỤC MỚI · Chỉ hiển thị trong lần này" });
   rows.Add("career.account.openLogin", new[] { "", "", "", "", "", "ĐĂNG NHẬP TÀI KHOẢN" });
   rows.Add("career.account.passwordLabel", new[] { "", "", "", "", "", "MẬT KHẨU (HOẶC MẬT KHẨU MỚI KHI KHÔI PHỤC)" });
   rows.Add("career.account.pasteHint", new[] { "", "", "", "", "", "Dán mật khẩu và mã được hỗ trợ. Đăng nhập sẽ kết thúc phiên đang mở trước khi đổi hồ sơ." });
   rows.Add("career.account.recover", new[] { "", "", "", "", "", "ĐỔI MẬT KHẨU BẰNG MÃ" });
   rows.Add("career.account.recoveryCodeLabel", new[] { "", "", "", "", "", "MÃ KHÔI PHỤC" });
   rows.Add("career.account.recoveryInputLabel", new[] { "", "", "", "", "", "MÃ KHÔI PHỤC (CHỈ CẦN KHI QUÊN MẬT KHẨU)" });
   rows.Add("career.account.register", new[] { "", "", "", "", "", "NÂNG CẤP HỒ SƠ" });
   rows.Add("career.account.rotateRecovery", new[] { "", "", "", "", "", "TẠO MÃ KHÔI PHỤC MỚI" });
   rows.Add("career.account.securityHint", new[] { "", "", "", "", "", "Tài khoản thuộc máy chủ này. Đăng nhập, đăng ký và đổi mật khẩu cần HTTPS. Mã khôi phục dùng một lần thay cho email; hãy tự lưu ở nơi riêng tư." });
   rows.Add("career.account.usernameLabel", new[] { "", "", "", "", "", "TÊN TÀI KHOẢN" });
   rows.Add("career.backup.contentLabel", new[] { "", "", "", "", "", "NỘI DUNG BẢN LƯU" });
   rows.Add("career.backup.export", new[] { "", "", "", "", "", "XUẤT BẢN LƯU" });
   rows.Add("career.backup.heading", new[] { "", "", "", "", "", "SAO LƯU LAN OFFLINE" });
   rows.Add("career.backup.import", new[] { "", "", "", "", "", "NHẬP BẢN LƯU" });
   rows.Add("career.backup.importConfirm", new[] { "", "", "", "", "", "Nhập bản lưu này? Máy chủ sẽ kiểm tra nguồn và tính hợp lệ trước khi thay thế tiến trình offline." });
   rows.Add("career.backup.onlineRestriction", new[] { "", "", "", "", "", "Sao lưu bằng văn bản chỉ dành cho hồ sơ LAN offline; dữ liệu online được quản lý trên máy chủ." });
   rows.Add("career.backup.privacyHint", new[] { "", "", "", "", "", "Bản lưu chỉ nhập lại vào hồ sơ offline này và phải qua kiểm tra máy chủ. Nội dung bản lưu có dữ liệu cá nhân; chỉ dán hoặc lưu ở nơi bạn tin cậy." });
   rows.Add("career.bike.compare", new[] { "", "", "", "", "", "SO VỚI {bike}\nGiới hạn tốc độ {difference} km/h\nHệ số 1× lấy Spark 450 làm mốc. Đây là thông số thiết kế trong game." });
   rows.Add("career.bike.equipped", new[] { "", "", "", "", "", "ĐANG DÙNG" });
   rows.Add("career.bike.owned", new[] { "", "", "", "", "", "ĐÃ SỞ HỮU" });
   rows.Add("career.bike.preview", new[] { "", "", "", "", "", "XEM 3D" });
   rows.Add("career.bike.previewTooltip", new[] { "", "", "", "", "", "Xem thiết kế {bike} và trở lại hồ sơ." });
   rows.Add("career.bike.stats", new[] { "", "", "", "", "", "GIỚI HẠN {speed} km/h  ·  TĂNG TỐC ×{acceleration}\nPHANH {braking} m/s²  ·  BÁM CUA ×{cornering}" });
   rows.Add("career.bikeDetail.available", new[] { "", "", "", "", "", "${cost} · CÓ THỂ MUA" });
   rows.Add("career.bikeDetail.equipped", new[] { "", "", "", "", "", "TÌNH TRẠNG {condition}% · ĐANG DÙNG" });
   rows.Add("career.bikeDetail.locked", new[] { "", "", "", "", "", "${cost} · CHƯA MỞ" });
   rows.Add("career.bikeDetail.owned", new[] { "", "", "", "", "", "TÌNH TRẠNG {condition}% · ĐÃ SỞ HỮU" });
   rows.Add("career.bikeList.locked", new[] { "", "", "", "", "", "{index}   {bike}\nCHƯA MỞ" });
   rows.Add("career.bikeList.lockedEquipped", new[] { "", "", "", "", "", "{index}   {bike}\nCHƯA MỞ · ĐANG DÙNG" });
   rows.Add("career.bikeList.owned", new[] { "", "", "", "", "", "{index}   {bike}\nĐÃ SỞ HỮU" });
   rows.Add("career.bikeList.ownedEquipped", new[] { "", "", "", "", "", "{index}   {bike}\nĐÃ SỞ HỮU · ĐANG DÙNG" });
   rows.Add("career.bikeList.price", new[] { "", "", "", "", "", "{index}   {bike}\n${cost}" });
   rows.Add("career.bikeList.priceEquipped", new[] { "", "", "", "", "", "{index}   {bike}\n${cost} · ĐANG DÙNG" });
   rows.Add("career.campaign.comingSoon", new[] { "", "", "", "", "", "SẮP RA MẮT" });
   rows.Add("career.campaign.complete", new[] { "", "", "", "", "", "ĐÃ HOÀN THÀNH HÀNH TRÌNH · Bạn có thể đua lại cấp hiện tại hoặc luyện tập tự do." });
   rows.Add("career.campaign.heading", new[] { "", "", "", "", "", "5 CẤP. 25 CHẶNG." });
   rows.Add("career.campaign.leaveRoom", new[] { "", "", "", "", "", "Rời phòng hiện tại trước khi tạo chặng của hành trình." });
   rows.Add("career.campaign.level", new[] { "", "", "", "", "", "CẤP {level}" });
   rows.Add("career.campaign.progressionHint", new[] { "", "", "", "", "", "Top 3 ở đủ 5 tuyến để lên cấp. Chọn một chặng thuộc cấp hiện tại; kết quả luyện tập không cộng vào hồ sơ máy chủ." });
   rows.Add("career.campaign.qualified", new[] { "", "", "", "", "", "ĐÃ QUA" });
   rows.Add("career.campaign.race", new[] { "", "", "", "", "", "ĐUA" });
   rows.Add("career.characters.accompanying", new[] { "", "", "", "", "", "ĐANG ĐỒNG HÀNH" });
   rows.Add("career.characters.choose", new[] { "", "", "", "", "", "CHỌN TAY ĐUA" });
   rows.Add("career.characters.connectProfile", new[] { "", "", "", "", "", "Kết nối hồ sơ đã lưu để chọn tay đua cho hành trình. Chế độ luyện tập cho phép thử mọi tay đua đã mở." });
   rows.Add("career.characters.expressionFocused", new[] { "", "", "", "", "", "Tập trung" });
   rows.Add("career.characters.expressionHappy", new[] { "", "", "", "", "", "Vui vẻ" });
   rows.Add("career.characters.expressionLabel", new[] { "", "", "", "", "", "XEM BIỂU CẢM" });
   rows.Add("career.characters.expressionNeutral", new[] { "", "", "", "", "", "Bình thường" });
   rows.Add("career.characters.heading", new[] { "", "", "", "", "", "CHỌN GƯƠNG MẶT CỦA HÀNH TRÌNH." });
   rows.Add("career.characters.inspect", new[] { "", "", "", "", "", "XEM TAY ĐUA" });
   rows.Add("career.characters.leaveRoom", new[] { "", "", "", "", "", "Rời phòng hiện tại trước khi đổi tay đua cho hồ sơ." });
   rows.Add("career.characters.portraitPending", new[] { "", "", "", "", "", "Ảnh chân dung sẽ xuất hiện khi nội dung được tải." });
   rows.Add("career.characters.ready", new[] { "", "", "", "", "", "SẴN SÀNG LÊN ĐƯỜNG" });
   rows.Add("career.characters.selected", new[] { "", "", "", "", "", "ĐANG CHỌN" });
   rows.Add("career.characters.selectionHint", new[] { "", "", "", "", "", "8 tay đua, mỗi người một phong cách. Lựa chọn thay đổi diện mạo; sức mạnh và phần thưởng giữ nguyên." });
   rows.Add("career.error.alreadyOwned", new[] { "", "", "", "", "", "Xe này đã có trong garage. Làm mới để chọn xe." });
   rows.Add("career.error.authRequired", new[] { "", "", "", "", "", "Hãy kết nối hồ sơ đã lưu hoặc đăng nhập tài khoản trước." });
   rows.Add("career.error.foreignSave", new[] { "", "", "", "", "", "Bản lưu thuộc hồ sơ hoặc máy chủ khác; không thể nhập vào hồ sơ này." });
   rows.Add("career.error.httpsRequired", new[] { "", "", "", "", "", "Đổi địa chỉ máy chủ sang wss:// để đăng nhập qua kết nối TLS." });
   rows.Add("career.error.insufficientCredits", new[] { "", "", "", "", "", "Quỹ chưa đủ cho giao dịch này. Hãy hoàn thành thêm chặng đua." });
   rows.Add("career.error.invalidCredentials", new[] { "", "", "", "", "", "Tên tài khoản, mật khẩu hoặc mã khôi phục chưa đúng." });
   rows.Add("career.error.invalidPassword", new[] { "", "", "", "", "", "Mật khẩu cần 12–128 ký tự. Hãy dùng một mật khẩu dài và riêng cho tài khoản." });
   rows.Add("career.error.invalidSave", new[] { "", "", "", "", "", "Bản lưu không hợp lệ hoặc đã bị thay đổi. Dùng bản xuất nguyên vẹn từ máy chủ." });
   rows.Add("career.error.invalidUsername", new[] { "", "", "", "", "", "Tên tài khoản cần 3–24 ký tự a–z, 0–9, dấu gạch dưới hoặc gạch nối." });
   rows.Add("career.error.networkUnavailable", new[] { "", "", "", "", "", "Không nhận được phản hồi. Kiểm tra kết nối; Thử lại giữ nguyên mã giao dịch." });
   rows.Add("career.error.notBankrupt", new[] { "", "", "", "", "", "Hồ sơ vẫn còn xe chạy được hoặc đủ quỹ sửa xe. Làm mới garage để tiếp tục hành trình." });
   rows.Add("career.error.profileBusy", new[] { "", "", "", "", "", "Rời phòng đua rồi thực hiện giao dịch này." });
   rows.Add("career.error.rateLimited", new[] { "", "", "", "", "", "Thao tác quá nhanh. Đợi một lát rồi thực hiện lại." });
   rows.Add("career.error.repairRequired", new[] { "", "", "", "", "", "Xe đang chọn đã hỏng. Sửa xe trước khi đổi hoặc đua." });
   rows.Add("career.error.staleSave", new[] { "", "", "", "", "", "Bản lưu đã cũ. Xuất bản mới nhất để bảo toàn giao dịch hiện tại." });
   rows.Add("career.error.storageUnavailable", new[] { "", "", "", "", "", "Máy chủ chưa lưu được dữ liệu. Thử lại sau; số dư chưa được xác nhận thay đổi." });
   rows.Add("career.error.unknown", new[] { "", "", "", "", "", "Chưa thực hiện được thao tác ({code}). Làm mới hồ sơ và kiểm tra dữ liệu vừa nhập." });
   rows.Add("career.error.usernameUnavailable", new[] { "", "", "", "", "", "Tên tài khoản đã có người dùng. Hãy chọn tên khác." });
   rows.Add("career.garage.bankruptNotice", new[] { "", "", "", "", "", "HÀNH TRÌNH ĐÃ DỪNG · Xe hỏng và quỹ không đủ sửa." });
   rows.Add("career.garage.browserHeading", new[] { "", "", "", "", "", "XE CỦA BẠN." });
   rows.Add("career.garage.conditionHeading", new[] { "", "", "", "", "", "TÌNH TRẠNG XE" });
   rows.Add("career.garage.empty", new[] { "", "", "", "", "", "Garage chưa có xe." });
   rows.Add("career.garage.equip", new[] { "", "", "", "", "", "CHỌN XE" });
   rows.Add("career.garage.leaveRoom", new[] { "", "", "", "", "", "Rời phòng trước khi đổi hoặc sửa xe." });
   rows.Add("career.garage.ownedHeading", new[] { "", "", "", "", "", "XE CỦA BẠN" });
   rows.Add("career.garage.previewHint", new[] { "", "", "", "", "", "Chọn xe để xem trước. Thay đổi xe dùng\nkhi máy chủ xác nhận." });
   rows.Add("career.garage.previewTooltip", new[] { "", "", "", "", "", "Xem trước {bike}" });
   rows.Add("career.garage.pristine", new[] { "", "", "", "", "", "XE NGUYÊN VẸN" });
   rows.Add("career.garage.repairButton", new[] { "", "", "", "", "", "SỬA XE · ${cost}" });
   rows.Add("career.garage.repairConfirm", new[] { "", "", "", "", "", "Sửa {bike} về 100% với ${cost}?" });
   rows.Add("career.garage.restart", new[] { "", "", "", "", "", "BẮT ĐẦU LẠI HÀNH TRÌNH" });
   rows.Add("career.garage.restartConfirm", new[] { "", "", "", "", "", "Bắt đầu lại từ đầu? Xe và chiến dịch hiện tại sẽ mất. Spark 450 trở về nguyên vẹn, quỹ $0. Tài khoản và lịch sử giao dịch được giữ lại." });
   rows.Add("career.garage.thumbnailPending", new[] { "", "", "", "", "", "Ảnh xe đang chờ bản render 3D được kiểm tra." });
   rows.Add("career.ledger.authorityHint", new[] { "", "", "", "", "", "Số dư và phần thưởng chỉ thay đổi sau khi máy chủ ghi nhận thành công." });
   rows.Add("career.ledger.balance", new[] { "", "", "", "", "", "SỐ DƯ ${balance}" });
   rows.Add("career.ledger.empty", new[] { "", "", "", "", "", "Chưa có giao dịch." });
   rows.Add("career.ledger.heading", new[] { "", "", "", "", "", "LỊCH SỬ GIAO DỊCH" });
   rows.Add("career.ledger.reasonBuy", new[] { "", "", "", "", "", "Mua xe" });
   rows.Add("career.ledger.reasonOpening", new[] { "", "", "", "", "", "Quỹ khởi đầu" });
   rows.Add("career.ledger.reasonRace", new[] { "", "", "", "", "", "Kết quả cuộc đua" });
   rows.Add("career.ledger.reasonRepair", new[] { "", "", "", "", "", "Sửa xe" });
   rows.Add("career.ledger.reasonRestart", new[] { "", "", "", "", "", "Bắt đầu lại hành trình" });
   rows.Add("career.ledger.reasonTrade", new[] { "", "", "", "", "", "Đổi xe" });
   rows.Add("career.ledger.unknownTime", new[] { "", "", "", "", "", "Thời gian chưa rõ" });
   rows.Add("career.notice.buy", new[] { "", "", "", "", "", "Đã thêm xe vào garage." });
   rows.Add("career.notice.character", new[] { "", "", "", "", "", "Đã chọn tay đua cho hành trình." });
   rows.Add("career.notice.default", new[] { "", "", "", "", "", "Tiến trình được máy chủ xác nhận. Có thể làm mới để cập nhật." });
   rows.Add("career.notice.equip", new[] { "", "", "", "", "", "Đã chọn xe cho chặng tới." });
   rows.Add("career.notice.export", new[] { "", "", "", "", "", "Bản lưu đã sẵn sàng. Chọn toàn bộ nội dung để sao chép." });
   rows.Add("career.notice.forget", new[] { "", "", "", "", "", "Đã bỏ khóa cũ trên máy này. Chọn KẾT NỐI HỒ SƠ để tạo hồ sơ mới, hoặc đăng nhập tài khoản." });
   rows.Add("career.notice.import", new[] { "", "", "", "", "", "Đã nhập bản lưu được máy chủ xác nhận." });
   rows.Add("career.notice.login", new[] { "", "", "", "", "", "Đăng nhập thành công." });
   rows.Add("career.notice.logout", new[] { "", "", "", "", "", "Đã thu hồi phiên và đăng xuất." });
   rows.Add("career.notice.recover", new[] { "", "", "", "", "", "Đã đổi mật khẩu. Hãy lưu mã khôi phục mới." });
   rows.Add("career.notice.register", new[] { "", "", "", "", "", "Đã nâng cấp hồ sơ. Hãy lưu mã khôi phục." });
   rows.Add("career.notice.repair", new[] { "", "", "", "", "", "Xe đã được sửa về 100%." });
   rows.Add("career.notice.restart", new[] { "", "", "", "", "", "Hành trình đã bắt đầu lại: Spark 450 nguyên vẹn, quỹ $0." });
   rows.Add("career.notice.rotateRecovery", new[] { "", "", "", "", "", "Đã tạo mã khôi phục mới. Mã cũ hết hiệu lực; hãy lưu mã mới." });
   rows.Add("career.notice.trade", new[] { "", "", "", "", "", "Đã đổi xe." });
   rows.Add("career.profile.connect", new[] { "", "", "", "", "", "KẾT NỐI HỒ SƠ" });
   rows.Add("career.profile.guestTransactions", new[] { "", "", "", "", "", "Phiên khách không thực hiện giao dịch hồ sơ." });
   rows.Add("career.profile.requiredTitle", new[] { "", "", "", "", "", "MỖI HÀNH TRÌNH CẦN MỘT HỒ SƠ." });
   rows.Add("career.profile.storageHint", new[] { "", "", "", "", "", "Hồ sơ được lưu trên máy chủ đang chọn. Khách mới và chế độ tập offline không tích lũy vào garage này." });
   rows.Add("career.shop.buyButton", new[] { "", "", "", "", "", "MUA THÊM · ${cost}" });
   rows.Add("career.shop.buyConfirm", new[] { "", "", "", "", "", "Mua {bike} với ${cost}?" });
   rows.Add("career.shop.compareHint", new[] { "", "", "", "", "", "Chọn một mẫu để so sánh với xe đang dùng. Giá, quyền sở hữu và tình trạng do máy chủ xác nhận." });
   rows.Add("career.shop.heading", new[] { "", "", "", "", "", "TÌM MỘT CẤU HÌNH PHÙ HỢP." });
   rows.Add("career.shop.leaveRoom", new[] { "", "", "", "", "", "Rời phòng trước khi đổi, mua hoặc sửa xe." });
   rows.Add("career.shop.trade", new[] { "", "", "", "", "", "ĐỔI XE" });
   rows.Add("career.shop.tradeConfirm", new[] { "", "", "", "", "", "Bán chiếc đang dùng với ${tradeValue} và mua {bike} với ${cost}?" });
   rows.Add("career.state.locked", new[] { "", "", "", "", "", "CHƯA MỞ" });
   rows.Add("career.status.awaitingConfirmation", new[] { "", "", "", "", "", "Đang chờ máy chủ xác nhận. Vui lòng đợi." });
   rows.Add("career.status.busy", new[] { "", "", "", "", "", "ĐANG XỬ LÝ · Chờ máy chủ xác nhận…" });
   rows.Add("career.summary.connectToSave", new[] { "", "", "", "", "", "Kết nối hồ sơ để lưu hành trình của bạn." });
   rows.Add("career.summary.empty", new[] { "", "", "", "", "", "Kết nối một hồ sơ để bắt đầu hành trình." });
   rows.Add("career.summary.endpoint", new[] { "", "", "", "", "", "MÁY CHỦ  {endpoint}" });
   rows.Add("career.summary.offline", new[] { "", "", "", "", "", "{player}   /   ${credits}   /   CẤP {level}   /   HỒ SƠ LAN · TÁCH BIỆT ONLINE" });
   rows.Add("career.summary.realm", new[] { "", "", "", "", "", "{player}   /   ${credits}   /   CẤP {level}   /   HỒ SƠ {realm}" });
   rows.Add("career.tabs.account", new[] { "", "", "", "", "", "TÀI KHOẢN" });
   rows.Add("career.tabs.campaign", new[] { "", "", "", "", "", "HÀNH TRÌNH" });
   rows.Add("career.tabs.characters", new[] { "", "", "", "", "", "TAY ĐUA" });
   rows.Add("career.tabs.garage", new[] { "", "", "", "", "", "GARAGE" });
   rows.Add("career.tabs.ledger", new[] { "", "", "", "", "", "GIAO DỊCH" });
   rows.Add("career.tabs.shop", new[] { "", "", "", "", "", "CỬA HÀNG" });
   rows.Add("common.cancel", new[] { "", "", "", "", "", "HỦY" });
   rows.Add("common.confirm", new[] { "", "", "", "", "", "XÁC NHẬN" });
   rows.Add("common.done", new[] { "", "", "", "", "", "XONG" });
   rows.Add("common.refresh", new[] { "", "", "", "", "", "LÀM MỚI" });
   rows.Add("common.retry", new[] { "", "", "", "", "", "THỬ LẠI" });
  }
 }
}
