<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup><ProjectReference Include="../RacingBois.Server.Application/RacingBois.Server.Application.csproj" /><PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" /></ItemGroup>
</Project>
