using System.Text.Json;
using RacingBois.Diagnostics.NativeProbe.Editor;
var rows=new List<object>();int failed=0;
void Check(bool value){if(!value)throw new InvalidOperationException();}
void Test(string name,Action action){try{action();rows.Add(new{name,passed=true});}catch(Exception error){failed++;rows.Add(new{name,passed=false,error=error.GetType().Name});}}
Test("unarmed_preflight_failure_performs_no_restoration_mutations",()=>{var scope=new NativeProbeBuildScope();Check(!scope.SettingsChanged&&scope.Restore().Length==0);});
Test("setter_partial_failure_is_rolled_back",()=>{int setting=7;var scope=new NativeProbeBuildScope();try{scope.ChangeSetting("backend",()=>{setting=9;throw new InvalidOperationException();},()=>setting=7);}catch(InvalidOperationException){}Check(setting==9&&scope.SettingsChanged);Check(scope.Restore().Length==0&&setting==7);});
Test("only_registered_owned_state_restores_in_reverse_order",()=>{var seen=new List<string>();var scope=new NativeProbeBuildScope();string unrelated="dirty-user-asset";scope.Own("active_scene",()=>seen.Add("active"));scope.Own("owned_scene",()=>seen.Add("own"));scope.ChangeSetting("backend",()=>seen.Add("apply"),()=>seen.Add("backend"));scope.ChangeSetting("apis",()=>{},()=>seen.Add("apis"));Check(scope.Restore().Length==0);Check(string.Join(",",seen)=="apply,apis,backend,own,active"&&unrelated=="dirty-user-asset");});
Test("one_restore_failure_does_not_abandon_later_cleanup",()=>{var seen=new List<string>();var scope=new NativeProbeBuildScope();scope.Own("own_scene",()=>seen.Add("closed"));scope.ChangeSetting("first",()=>{},()=>seen.Add("first"));scope.ChangeSetting("last",()=>{},()=>throw new IOException());var errors=scope.Restore();Check(errors.Length==1&&errors[0]=="last:IOException"&&string.Join(",",seen)=="first,closed");});
Test("scene_only_scope_does_not_claim_setting_changes",()=>{var scope=new NativeProbeBuildScope();int closes=0;scope.Own("own_scene",()=>closes++);Check(!scope.SettingsChanged&&scope.Restore().Length==0&&closes==1);});
Test("restore_is_idempotent_and_closed_scope_rejects_writes",()=>{var scope=new NativeProbeBuildScope();int count=0;scope.Own("own",()=>count++);scope.Restore();scope.Restore();bool rejected=false;try{scope.ChangeSetting("late",()=>count++,()=>{});}catch(InvalidOperationException){rejected=true;}Check(count==1&&rejected);});
string output=args[0];Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);File.WriteAllText(output,JsonSerializer.Serialize(new{passed=failed==0,tests=rows.Count,failed,results=rows,scope="Actual pure rollback-journal behavior. No Unity Editor lifecycle or asset save was invoked."},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine($"LIFECYCLE {(failed==0?"PASS":"FAIL")} {rows.Count}");return failed==0?0:1;
