<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><LangVersion>9.0</LangVersion><ImplicitUsings>disable</ImplicitUsings><Nullable>disable</Nullable></PropertyGroup>
  <ItemGroup><ProjectReference Include="../RacingBois.Protocol/RacingBois.Protocol.csproj" /><ProjectReference Include="../RacingBois.Simulation/RacingBois.Simulation.csproj" /><Compile Include="../../../Packages/com.racingbois.foundation/Runtime/NetworkMapping/**/*.cs" Link="%(Filename)%(Extension)" /></ItemGroup>
</Project>
